// import type { Metadata } from "next";
// import { Inter } from "next/font/google";
// import "./globals.css";
// import { Toaster, toast } from "sonner";
// import Html from "./components/Html";
// import { useState } from "react";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Share Thoughts",
//   // description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   return (
//     <Html>
//       {children}
//       <Toaster position="top-center" />;
//     </Html>
//   );
// }
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Share Thoughts",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark" className="w-screen">
      <body className={inter.className + " w-full overflow-x-hidden"}>
        {children}
        <Toaster position="top-center" />
      </body>
    </html>
  );
}
